name: test
 
on:
  push:
    branches:
      - main
 
jobs:
  hello_world:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Print Hello World
      run: echo "Hello, World!"
